# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from test/PIDInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class PIDInfo(genpy.Message):
  _md5sum = "92edbf2a438afd03b29a449025eeb3aa"
  _type = "test/PIDInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose2D error
geometry_msgs/Pose2D desired
geometry_msgs/Pose2D actual
================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta"""
  __slots__ = ['error','desired','actual']
  _slot_types = ['geometry_msgs/Pose2D','geometry_msgs/Pose2D','geometry_msgs/Pose2D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       error,desired,actual

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PIDInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.error is None:
        self.error = geometry_msgs.msg.Pose2D()
      if self.desired is None:
        self.desired = geometry_msgs.msg.Pose2D()
      if self.actual is None:
        self.actual = geometry_msgs.msg.Pose2D()
    else:
      self.error = geometry_msgs.msg.Pose2D()
      self.desired = geometry_msgs.msg.Pose2D()
      self.actual = geometry_msgs.msg.Pose2D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.error.x, _x.error.y, _x.error.theta, _x.desired.x, _x.desired.y, _x.desired.theta, _x.actual.x, _x.actual.y, _x.actual.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.error is None:
        self.error = geometry_msgs.msg.Pose2D()
      if self.desired is None:
        self.desired = geometry_msgs.msg.Pose2D()
      if self.actual is None:
        self.actual = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.error.x, _x.error.y, _x.error.theta, _x.desired.x, _x.desired.y, _x.desired.theta, _x.actual.x, _x.actual.y, _x.actual.theta,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.error.x, _x.error.y, _x.error.theta, _x.desired.x, _x.desired.y, _x.desired.theta, _x.actual.x, _x.actual.y, _x.actual.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.error is None:
        self.error = geometry_msgs.msg.Pose2D()
      if self.desired is None:
        self.desired = geometry_msgs.msg.Pose2D()
      if self.actual is None:
        self.actual = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.error.x, _x.error.y, _x.error.theta, _x.desired.x, _x.desired.y, _x.desired.theta, _x.actual.x, _x.actual.y, _x.actual.theta,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
