(cl:in-package aimbot-msg)
(cl:export '(VISION_X-VAL
          VISION_X
          VISION_Y-VAL
          VISION_Y
          VISION_THETA-VAL
          VISION_THETA
          XHAT-VAL
          XHAT
          YHAT-VAL
          YHAT
          THETAHAT-VAL
          THETAHAT
          VX-VAL
          VX
          VY-VAL
          VY
          W-VAL
          W
          XHAT_FUTURE-VAL
          XHAT_FUTURE
          YHAT_FUTURE-VAL
          YHAT_FUTURE
          THETAHAT_FUTURE-VAL
          THETAHAT_FUTURE
          PREDICT_FORWARD_SECONDS-VAL
          PREDICT_FORWARD_SECONDS
          CORRECTION-VAL
          CORRECTION
))